### DISCUSSION TITLE
[TEMPLATE]: Using CDN to deliver assets

### DISCUSSION THREAD

**Discussion by Mara-Li** [ObsidianPublisher/obsidian-github-publisher#114] [Announcements]
Hello everyone!
Because I needed to keep the repo clean, I add the idea to use a `overrides` html file to import css & js linked to the template. After some reflection, and because I was difficult to keep updated all repo for template, I choose to use [jsdelivr](https://www.jsdelivr.com/).

So, the template assets are in a new `assets` repository ([follow_template](https://github.com/ObsidianPublisher/follow_template) will be kept for other file, as override). A github action will build a new mono-file for JS and CSS. 

To use it, you just need to clean your `mkdocs.yml` and update the `extra_css` and `extra_javascript` as follow : 

```yaml
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets/dist/javascript.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets/dist/styles.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
```

and that's it :D
