### DISCUSSION TITLE
[TEMPLATE]: Reusable workflows

### DISCUSSION THREAD

**Discussion by Mara-Li** [ObsidianPublisher/obsidian-github-publisher#154] [Announcements]
Hello everyone!

I got tired of checking and updating everything across multiple repositories when working on GitHub action workflows. Using sync was helpful but sometimes tricky, as I wasn't sure what was affecting what.

I spent the whole day searching for a solution to reuse workflows across repositories without having to publish them. And guess what? I found it!

Introducing a new repository: [ObsidianPublisher/actions](https://github.com/ObsidianPublisher/actions). This repository contains all the workflows used to accomplish the following tasks:

- Update the template (from [ObsidianPublisher/sync_template](https://github.com/ObsidianPublisher/sync_template)).
- Deploy to Netlify/Vercel/GitHub Pages (depending on your configuration and whether you want the graph).
- Perform maintenance tasks such as cleaning unused images and updating your `requirements.txt`.
- Create an index.

These new reusable workflows are easier to read and update. Now, I only need to update one repository, and you'll automatically get the latest version. Moreover, you can customize them as per your requirements. For example, you can add specific actions during the deployment process.

**Comment by Mara-Li** [comment]
Update: I spotted that the `git push` action used in workflow (index, deploy and maintenance) was broken if the branch was protected.

To fix that, and support branch protection, I added the `secrets` (not required) `author_email` and `author_name`.

If you need to use them for your workflow, you need to update:
- `maintenance.yml`
- `deploy.yml`
- `index.yml`

For example, in `maintenance.yml`:
```yaml
name: Repository maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:      
    uses: ObsidianPublisher/actions/.github/workflows/maintenance.yml@main
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
      AUTHOR_NAME: ${{ secrets.AUTHOR_NAME}}
```

By default, the `author_email` will be `github-actions[bot]@users.noreply.github.com` and `author_name` : `github-actions[bot]`
