### DISCUSSION TITLE
FR Backlinks at the bottom of note

### DISCUSSION THREAD

**Discussion by efemkay** [ObsidianPublisher/obsidian-github-publisher#168] [Ideas]
Similar to obisidian core plugin which allow backlinks in document at the bottom.

Backlinks feature can be useful for both digital garden as well as documentation site. I've seen implementation using Jekyll and liquid template before (by iterating backlinks matching during build). Perhaps also doable with MkDocs template?

Let me know if you need further details. Thanks.

**Comment by Mara-Li** [comment]
Hello.
I don't plan to develop this feature.

You can check:
- [mkdocs-publisher package](https://mkusz.github.io/mkdocs-publisher/setup/pub-obsidian/), developped by @mkusz, which have this feature ;
- Check [this gh-pages build with github action](https://github.com/ObsidianPublisher/template-gh-pages/pull/12):
```yaml
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
        with:
          repository: 'hannesdelbeke/note-link-janitor'  # use fork to support subfolders
          ref: stable
          path: 'note-link-janitor'
      - name: install yarn in janitor workspace
        run: |
            cd ${{ github.workspace }}/note-link-janitor
            yarn install
            yarn run build
      - name: Run Note Link Janitor
        run: ${{ github.workspace }}/note-link-janitor/dist/index.js ${{ github.workspace }}/docs
      - name: Remove Janitor folder
        run: rm --force -r note-link-janitor
  ```
  This action must be done **before** page building (`mkdocs build`).
