### DISCUSSION TITLE
Adding support to render in page metadata for dataview

### DISCUSSION THREAD

**Discussion by nghiango1** [ObsidianPublisher/obsidian-github-publisher#199] [Ideas]
In the dataview doc [Adding Metadata to your Pages](https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/) support this type of way to add metadata, specify this use case

> There is also the alternative parenthesis syntax, which hides the key when rendered in Reader mode: 
  `This will not show the (longKeyIDontNeedWhenReading:: key).`
  will render to:
  `This will not show the key.`

Example: 
In the edit mode, I adding this

(language:: python)

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/31164703/8d3d2649-b007-41ac-8c3c-0e1b3a1e18d5)

Which, dataview will help render out all the only python in web view

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/31164703/f732aefa-96bc-47a2-93db-89fb6a1ada68)

But in the build static site, it still appear as 

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/31164703/1b892127-dd44-4153-9362-e1960548beca)

Is theres any way too help with this?

**Comment by Mara-Li** [comment]
It's a little surprising. I use the API of Dataview to convert the page and I didn't expect this type of behavior.

I need to check the API to see if I can do something.

But, it is simpler to use regex to hide them, like: `(.*)::(.*)` → `$2` 
See : https://regex101.com/r/hlb2vD/2

**Reply by nghiango1** [reply]
This should be fine enough, I try add

```python
markdown = re.sub(r'\((.+):: *(.+)\)', r'`\2`', markdown)
```

and it work, but `chore: autopublish` seem just mad at me and revert the change every now and then. How to stop it, I try adding EXCLUDED-FILES in update.yml but it still happen.

How to do it exactly

```yml
name: Get latest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
      EXCLUDED-FILES: "overrides/hooks/on_page_markdown.py"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
