### DISCUSSION TITLE
Assets optimization

### DISCUSSION THREAD

**Discussion by Mara-Li** [ObsidianPublisher/obsidian-github-publisher#208] [Show and tell]
If you're similar to me, you might find yourself dealing with an excessive number of images, which can significantly extend the building process. This issue becomes even more pronounced without the utilization of the optimize plugin (available at [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin)), as this feature is exclusively offered to sponsors.

In light of this, I made the decision to devise a new workflow. This workflow is designed to run daily and on-demand, leveraging the capabilities of [calibre/calibreapp/image-actions](https://github.com/calibreapp/image-actions/) to address this challenge.

Allow me to present the details of the workflow:
```yaml
name: Optimize images on PR
on:
    schedule:
    - cron: "0 0 * * *"
    workflow_dispatch:
    
jobs:
    optimize-images:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: optimize
              uses: calibreapp/image-actions@main
              with:
                githubToken: ${{ secrets.GITHUB_TOKEN}}
                ignorePaths: "overrides/.icons/**"
                compressOnly: true
            - name: "Commit & push"
              uses: actions-js/push@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
                message: "[CI] Optimize images"
```

It will commit and push directly to the 'main' branch, but you can modify the final section to generate a pull request along with a summary. Personally, I opt to steer clear of pull requests in my situation due to an already excessive number (over 1,000 PRs accomplished!) caused by the plugin's effects. 😄
