### DISCUSSION TITLE
Publishing with the repository template and dataview queries is not working

### DISCUSSION THREAD

**Discussion by rajbos** [ObsidianPublisher/obsidian-github-publisher#268] [General]
Hi, I'm trying to publish our Obsidian content to GitHub Pages using the GitHub [repository template](https://github.com/ObsidianPublisher/mkdocs-publisher-template). Thanks for the work with an easy setup for this!

So far things like Mermaid charts and Navigation footers are working, except the `dataview` queries: they are converted to html as is, and I cannot get them to work. Any info to get me in the right direction would be appreciated!

I've tried both the template and the Obsidian plugin [obsidian-github-publisher](https://github.com/ObsidianPublisher/obsidian-github-publisher) but it seems those are two completely different setups? The plugin does transform the dataview queries into the right markdown!

Is there a way to combine things? What I want to achieve is that I can work in Obsidian locally (the queries work just fine) and on commit+push into the GitHub repo I want to publish the docs into a GitHub Pages website, with a GitHub Actions workflow without any manual action (like the plugin would be).

Is there something I am missing in the template for this? Or is this use case not supported at all?

**Comment by Mara-Li** [comment]
Have you enabled the dataview option in the settings ? The dataview transformation into Markdown is not linked with the template.

**Comment by rajbos** [comment]
I don't see a reference to that setting in the docs, so probably not 😄 (also can't find it in the `mkdocs.yml` indeed

**Reply by Mara-Li** [reply]
The dataview transformation have nothing in common with the template, you don't need to use it for that.
And huh. Please, read better the documentation ^^" : https://obsidian-publisher.netlify.app/plugin/settings/content/?h=dataview#main-text

**Reply by rajbos** [reply]
That's the docs for the plugin, which is working fine. I want to do this in the publish to GitHub Pages using [the repository template](https://github.com/ObsidianPublisher/mkdocs-publisher-template) 😄 .

**Reply by rajbos** [reply]
I'm hoping there is a setting in the mkdocs.yml that I can do to trigger this correctly, like for example in here:

``` yaml
extra:
  comments: false #disable comments globally
  generate_graph: false #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: true #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: false
    fix_heading: true
```
