### DISCUSSION TITLE
4.6.0 Beta !

### DISCUSSION THREAD

**Discussion by Mara-Li** [ObsidianPublisher/obsidian-github-publisher#43] [Announcements]
Hello! 
A new beta cycle start now! 
Until two weeks, the update will stay in **beta** (you can install beta directly throught BRAT).

The beta adds a new possibility : send a file in multiple repository in the same times.

To do this, you need to use the key `multipleRepo` in a YAML object, as follow : 
```yaml
multipleRepo: 
  - repo:
      branch: string #change default branch 
      repo: string #change default repository
      owner: string #change default owner (it's your github Username)
      autoclean: boolean #enable auto cleaning
  - repo:
      branch: 
      repo: 
      owner: 
      autoclean: 
```

Note : By default, autoclean is disabled.

You can, also, use a string to set multiple repo : 
```yaml
multipleRepo:
  - username/repo/branch/autoclean
  - username/repo/branch
  - username/repo
  - repo
```
