### ISSUE TITLE
[MKDOCS][Bug]: Duplicate comments

### ISSUE THREAD

**Issue by yshalsager** [ObsidianPublisher/obsidian-github-publisher#193]
### Material General discussion

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Requirements

```bash session
mkdocs==1.5.2
mkdocs-material==9.1.21
mkdocs-ezlinked-plugin==0.3.3
mkdocs-awesome-pages-plugin==2.9.1
mdx_breakless_lists==1.0.1
mkdocs-preview-links-plugin==0.6.2
mkdocs-embed-file-plugins==2.0.6
mkdocs_custom_fences==0.1.2
mkdocs-git-revision-date-localized-plugin==1.2.0
mkdocs-encryptcontent-plugin==2.5.3
mkdocs-callouts==1.9.0
mkdocs-custom-tags-attributes==0.3.0
mkdocs-meta-descriptions-plugin==2.3.0
obsidiantools==0.10.0
pyvis==0.3.2
cairosvg==2.7.1
pillow==10.0.0
mkdocs-glightbox==0.3.4
mkdocs-minify-plugin==0.7.1
```

### Mkdocs.yml

```YAML
site_name: ...
site_description: ...
site_url: ...

theme:
  name: "material"
  logo: assets/meta/icon.png
  favicon: assets/meta/icon.png
  custom_dir: overrides
  font:
    code: Noto Sans Mono
  direction: auto
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy

# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search:
      lang:
        - en
        - ar
  - meta-descriptions
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: en
      custom_format: "%Y-%m-%d"
      enable_creation_date: true
  - ezlinks:
      wikilinks: true
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: "assets/css/custom_attributes.css"
  - custom-attributes:
      file: "assets/css/custom_attributes.css"
  - tags:
      tags_file: tags.md
  - encryptcontent:
      title_prefix: "🔐"
      summary: "Private page"
      placeholder: "Password"
      decryption_failure_message: "Invalid password"
      encryption_info_message: "You don't have access to this page."
      search_index: "encrypted"
      password_button: True
      password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1em" width="1em"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c17.67 0 32 14.33 32 32v256c0 17.67-14.33 32-32 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c53.02 0 96-42.98 96-96V128C512 74.98 469 32 416 32zM342.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L242.8 224H32C14.31 224 0 238.3 0 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C355.1 266.1 355.1 245.9 342.6 233.4z"/></svg>'
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py
extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/js/custom.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/styles.css
  - assets/css/admonition.css
  - assets/css/custom_attributes.css
  - assets/css/customization.css
extra:
  SEO: /assets/meta/icon.png
  comments: true #disable comments globally
  generate_graph: false #generate the graph of the site
  attachments: "assets/img" #path to the folder where the attachments are stored
  no-auto-h1: false #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: "posts in" #message to display before the number of posts ; Add your own translation!
    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: true
    fix_heading: true
```

### Error

```bash session
Nothing
```

### Bug description

There are two comments sections added in any page with enabled comments. Apparently this is because comments partial is included twice in GH pages template.

https://github.com/ObsidianPublisher/template-gh-pages/blob/646378b6620576f5eb9db7219d05aed2ad7945c7/overrides/main.html#L26

https://github.com/ObsidianPublisher/template-gh-pages/blob/646378b6620576f5eb9db7219d05aed2ad7945c7/overrides/partials/content.html#L54

### Steps to reproduce

Add giscus comment system and enable it.

### Expected behavior

Comments section is shown once.

### Screenshots

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/17043808/febae97a-a275-4955-b603-38db5a00c9ec)

### Additional context

You can check the problem live [here](https://notes.yshalsager.com/).
