### ISSUE TITLE
[MKDOCS][Bug]: Missing inputs github token

### ISSUE THREAD

**Issue by andreicozma1** [ObsidianPublisher/obsidian-github-publisher#215]
### Material General discussion

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Requirements

```bash session
mkdocs==1.5.2
mkdocs-material==9.2.5
mkdocs-ezlinked-plugin==0.3.3
mkdocs-awesome-pages-plugin==2.9.2
mdx_breakless_lists==1.0.1
mkdocs-preview-links-plugin==0.6.2
mkdocs-embed-file-plugins==2.0.6
mkdocs_custom_fences==0.1.2
mkdocs-git-revision-date-localized-plugin==1.2.0
mkdocs-encryptcontent-plugin==2.5.3
mkdocs-callouts==1.9.0
mkdocs-custom-tags-attributes==0.3.0
mkdocs-meta-descriptions-plugin==2.3.0
obsidiantools==0.10.0
pyvis==0.3.2
cairosvg==2.7.1
pillow==10.0.0
mkdocs-glightbox==0.3.4
mkdocs-minify-plugin==0.7.1
```

### Mkdocs.yml

```YAML
site_name: "Andrei's Public Notes" # Change this to your site name
site_description: 'A chunk of my notes which I chose to share with the public.'
site_url: https://andreicozma.com/public-notes/ # Change this to your site URL

theme:
  name: 'material'
  logo: assets/meta/logo.jpg
  favicon: assets/meta/favicon.jpg
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: en
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - meta-descriptions
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: en
      custom_format: '%A %d %B %Y'
      enable_creation_date: true
  - ezlinks:
      wikilinks: true
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - tags:
      tags_file: index.md
  - encryptcontent:
      title_prefix: '🔐'
      summary: 'Private page'
      placeholder: 'Password'
      decryption_failure_message: 'Invalid password'
      encryption_info_message: "You don't have access to this page."
      search_index: 'encrypted'
      password_button: True
      password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1em" width="1em"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c17.67 0 32 14.33 32 32v256c0 17.67-14.33 32-32 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c53.02 0 96-42.98 96-96V128C512 74.98 469 32 416 32zM342.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L242.8 224H32C14.31 224 0 238.3 0 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C355.1 266.1 355.1 245.9 342.6 233.4z"/></svg>'
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py
extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/styles.css
  - assets/css/admonition.css
  - assets/css/custom_attributes.css
  - assets/css/customization.css
extra:
  SEO: assets/meta/SEO.png
  comments: false #disable comments globally
  generate_graph: true #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: false #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
    no_page_found: 'No pages found!' #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: true
    fix_heading: true
```

### Error

```bash session
Run actions-js/push@master
Started: bash /home/runner/work/_actions/actions-js/push/master/start.sh
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/actions-js/push/master/start.js:9:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/actions-js/push/master/start.js:9:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### Bug description

Automatic "Get latest release from template" workflow fails.

The logs say:
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".

however can't add GITHUB_TOKEN secret because it starts with GITHUB, so it seems like the error is coming from somewhere else.

### Steps to reproduce

Nothing, the template is scheduled to run on a scheduled basis

### Expected behavior

Automatic workflow expected to finish successfully.
